### ISSUE TITLE
expansion fails at the beginning of the line.

### ISSUE THREAD

**Issue by arnauqb** [brennier/vimtexer#11]
First of all, thank you for this great plugin, it is making my life much easier. Now I have an issue whenever I type something like
delta hat
you would expect this (I am using the default dictionary here) to expand as
\hat{\delta}
which is usually what happens. However, whenever this is typed in the beginning of the equation, the expansion fails and vim goes back to normal mode. I attach a shitty gif for details.
![issue](https://user-images.githubusercontent.com/21260922/28772377-50a32e16-75e6-11e7-8dfa-850bc4a8d218.gif)

**Comment by brennier** [comment]
I assume that you use tabs instead of spaces? In any case, I just pushed a commit that should fix your problem. Update the plugin and check to see if the problem still persists just in case.

**Comment by arnauqb** [comment]
Thank you for your answer. I use the default space key as trigger. The problem still persists.

**Comment by brennier** [comment]
I just meant that I assume the whitespace before your example is a tab and not four spaces. In any case, I was fairly confident that I found/fixed the source of your problem. Could you please confirm that this is the entry for 'hat' in your default dictionary (The default dictionary is located at `ftplugin/tex/default_keywords.vim`.):
```vim
    \'hat'  : "\<ESC>xBi\\hat{\<ESC>Ea} ",
```

**Comment by arnauqb** [comment]
Hello,
Thank you for your time. The update had no effect because I was running a custom dictionary, I tried with the updated default one but the problem now is that it puts the \hat to the \begin{equation}, like the screenshot shows. 
![screenshot from 2017-08-02 22-35-36](https://user-images.githubusercontent.com/21260922/28893858-3e140dd0-77d3-11e7-97e3-6ea57439fa5c.png)

**Comment by brennier** [comment]
Ah, yes, it seems the fix I implemented failed on single characters. It should be working now. Please update the plugin and check once more.

**Comment by arnauqb** [comment]
Great! Working perfect now!
Thank you very much!
