### ISSUE TITLE
Does not trigger for .R filetype

### ISSUE THREAD

**Issue by be5tan** [brennier/vimtexer#12]
Hi,
I wanted to try using your plugin also for .R files. I added 
```
let g:quicktex_R = { 
    \' '   : "\<ESC>/<+.*+>\<CR>\"_c/+>/e\<CR>",
    \'m'   : '\( <+++> \) <++>',
    \'prf' : "\\begin{proof}\<CR><+++>\<CR>\\end{proof}",
\}
```
to my .vimrc. However, it did not trigger. In .tex files everything works perfectly. Do you know what my mistake is?

**Comment by brennier** [comment]
Rename `g:quicktex_R` to `g:quicktex_r`.

In the future, the command `:echo &filetype` will display what vim calls the filetype of your file.

**Comment by be5tan** [comment]
Thank you. This solved it. By the way thank you for the great plugin, I use it every day.

**Comment by brennier** [comment]
No problem, I'm glad to help
