### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by andportnoy** [brennier/vimtexer#15]
Dear Bennett,

QuickTeX is absolutely stunning, I submitted it to VimAwesome as I think more people should be using it.

Thank you so much for your work!

Andrey.

**Comment by brennier** [comment]
Ah, thank you! I'll be merging the 'modes' branch to master soon, which will allow one to specify delimiters and use your own custom dictionaries (similar to how there are separate tex and math dictionaries). I'm also in the middle of adding an option to trigger on non-word characters, which would make QuickTex behave more similarly to abbreviations.
