### ISSUE TITLE
\\[34ex] is read as the beginning of math mode

### ISSUE THREAD

**Issue by cpctheman** [brennier/vimtexer#16]
Hello,

Encountered an interesting issue where my mathmode expansions would trigger outside of a math environment, but my regular expansions wouldn't.  After some trial and error, I realized the issue was on lines after I created some vertical space with \\\\[34ex].  I believe quicktex reads \\\\[ as the beginning of the usual math mode delineated by \\[ \\], but without a closing \\] in sight, it registers that I am in mathmode for the rest of the document.

This is easily fixed by changing \\\\[34ex] to \\\\ \[34ex\] (or even just using \vspace), but I wonder if this could be remedied from within quicktex.

**Comment by brennier** [comment]
You're absolutely right. I've just added a commit to fix this.
