### ISSUE TITLE
Script with quicktex_pandoc must be loaded before plugin scripts

### ISSUE THREAD

**Issue by fflores97** [brennier/vimtexer#17]
Since the `ftplugin/pandoc.vim` script creates an empty dictionary if a `g:quicktex_pandoc` hasn't been created at the moment of loading, custom dictionaries won't work if executed after `ftplugin/pandoc.vim`. To fix this, I just made sure to source my custom dictionary **before the plugin**. That is, in my `.vimrc` you'd see something like

```
source ~/.vim/quicktex_script.vim
Plugin 'brennier/quicktex'
```
Where `~/.vim/quicktex_script.vim` would contain
```
let g:quicktex_pandoc = {
...
}
```
And it worked like a charm. Just wanted to leave this here to help future pandoc users that might have the same issues I had. It's a very nice plugin. Nice work!

**Comment by brennier** [comment]
This should no longer be necessary with my latest commits. Quicktex now checks if a dictionary exists before trying to look up a keyword. Thus, the `ftplugin/pandoc.vim` file no longer creates empty dictionaries.
