### ISSUE TITLE
Math Mode Support for Markdown Files

### ISSUE THREAD

**Issue by collinschad** [brennier/vimtexer#18]
Hello,

Is there currently any way to include the math mode dictionaries within markdown files? In expand.vim it looks like there's some consideration for pandoc files, but I'm not sure how to implement this with straight .md files. If not a current feature, is this planned for the future?

FYI I love your plugin and it has greatly improved my workflow.

It looks like I'd just need to add the option `a:ft == 'md'` to the conditional concerning mathmode in expand.vim. Would this work?

**Comment by brennier** [comment]
Sorry for the late response; I've been busy in graduate school. You can do as you suggest and just add the `a:ft == 'md'` to the conditional if you just need to work with the typical $ signs. There's also another branch of this repository called `modes` that allow you to add your own context-dependent expansions. For example, you could set up separate dictionaries for javascript and css code inside of an markdown file. Such an example would be set up like this:
```
let g:quicktex_modes = [
    " The format is [filetype, name of dictionary, list of starting keywords, list of ending keywords]
    \['md', 'js', ['```js'], ['```']]
    \['md', 'css', ['```css'], ['```']]
\]
let g:quicktex_js = {
    " Set up as typical dictionary
\}
let g:quicktex_css = {
    " Set up as typical dictionary
\}
```

**Comment by Gaaruda** [comment]
@brennier I am new to the vim can you please help me how to edit it .
![image](https://user-images.githubusercontent.com/80031164/120931599-e546ee80-c70f-11eb-911b-6c9b96fb1566.png)
 
here is mine expand.vim

**Comment by brennier** [comment]
I don't see anything wrong. It looks like you made the change correctly.
