### ISSUE TITLE
Change place markers?

### ISSUE THREAD

**Issue by engeljh** [brennier/vimtexer#21]
Hi,

Might you be able to allow users to choose their own place markers, i.e. change <+ and +> to other key combinations, as Latex Suite does?  Would be much appreciated.

**Comment by brennier** [comment]
The markers `<+` and `+>` are only referenced in the dictionaries that you use for expansions. If you'd like to use a different marker, then you need only to change your dictionaries to reference your desired markers instead. (Keep in mind that the act of "jumping to the next <++>" is itself an expansion.)

There is one exception to this, which is for the marker `<+++>`. This marker is special and designates where to place the cursor after expansion. However, changing this marker isn't worth the trouble as it never actually appears when typing.
