### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [brennier/vimtexer#25]
What would prevent someone from using this plugin for other languages than LaTeX? For instance python. Any technical details that make it not worth it to generalize? Maybe similar-functionality vim plugins already exist?

**Comment by brennier** [comment]
There's nothing to prevent you from using this with other languages. I use it for that very purpose as well, which is which I added dictionary support for filetypes other than LaTeX.

The vim plugin "Ultisnips" or some other snippet program would be a better choice, though. Ultisnips has a lot of additional functionality, which you may be interested in, such as support for multiple cursors and the ability to write expansions in Python. You can see a short comparsion in the README. The main advantage of QuickTex is the separate namespaces for being inside of math-mode and being outside of math-mode, which obviously doesn't matter for other languages.

**Comment by make-github-pseudonymous-again** [comment]
Ok. I think in Python you would want to treat text in string literals and comments differently than the code which is similar to the separate namespace and detection this project has for math mode. I'll check Ultisnips out.

**Comment by ghost** [comment]
If I wanted to use quicktex for markdown documents with equations, what would I have to do?
- I have added the condition `a:ft == 'md'` in the `expand.vim` file `if` statement
- I created `md.vim` with my own dictionary in the `ftplugin` directory

For some reason it doesn't seem to work. Is there something else I need to do?
Thanks a lot for your help!

**Comment by brennier** [comment]
I believe Vim's filetype for markdown is `markdown`, not `md`. Change your condition to `a:ft == 'markdown'` and your file in `ftplugin` to `markdown.vim`. Hopefully it will work after that.

**Comment by ghost** [comment]
Yes it worked! Thank you so much!

**Comment by lauswullum** [comment]
Hi, Thank you very much for this Plugin!

Do you know how I would go about using this plugin for `.qmd.` (quarto) files?
I have already added the conditions
- `    if (a:ft == 'tex' || a:ft == 'pandoc' || a:ft == 'quarto' || a:ft == 'markdown' ) && quicktex#mathmode#InMathMode()`
in line 19 of `expand.vim`.  

But I need advice on how to structure my `quarto.vim` and `markdown.vim` files in the `ftplugin` folder.

**Comment by lauswullum** [comment]
Got It to work by adding the following file quarto.vim
```vim
if !get(g:, 'quicktex_quarto_enable', 1)
    finish
endif

if exists('g:quicktex_quarto') && !exists('g:quicktex_math')
    let g:quicktex_math = {}
elseif !exists('g:quicktex_quarto') && exists('g:quicktex_math')
    let g:quicktex_quarto = {}
endif

" LaTeX Mode Keywords {{{
let g:quicktex_quarto = {...
```

**Comment by brennier** [comment]
Yes, that works. Since there seem to be more and more formats using LaTeX's math syntax, I'll update the code so that you can specify which filetypes support math mode.

**Comment by brennier** [comment]
It's been done. You can now set which filetypes use math mode by modifying `g:quicktex_math_filetypes`. The default includes `tex`, `pandoc`, and `markdown`.

@lauswullum:
Add `let g:quicktex_math_filetypes = ['tex', 'pandoc', 'markdown', 'quarto']` to to your `.vimrc` to make sure that  `quatro` files also use the math dictionary. Also, the plugin now checks if a dictionary exists before doing a keyword lookup, so you no longer need those `if` statements which make empty dictionaries if they haven't been set. You can simply make a file called `ftplugin/quarto.vim` and set the variable `let g:quicktex_quarto = { ... }` and that should be everything. If you still have problems, feel free to open a new bug.
