### ISSUE TITLE
Extraneous text appears after keyword expansion

### ISSUE THREAD

**Issue by AlekseiSmirnov** [brennier/vimtexer#3]
Extraneous text appears after keyword expansion when I type fastly. 
For example, if you type `frac <space> s`,  `:normal vs` phrase replaces `<+++>`

![vimtexer1](https://cloud.githubusercontent.com/assets/10200871/23995520/ff4525ca-0a5a-11e7-9a20-022efb8124ac.gif)

**Comment by brennier** [comment]
I can't seem to recreate this. Also, I doubt that this is Vimtexer's fault, as there's not a single "normal" call in the whole program. It seems like this is the fault of another plugin that you have installed or perhaps something in your vimrc. Could you run `:profile start output.log | profile func * | profile file *`, type something that causes this problem, exit vim, and then upload the output.log to this thread?

**Comment by AlekseiSmirnov** [comment]
Can't reproduce this problem now. It seems that when I reload .vimrc `(:source $MYVIMRC<CR>
)` file on warm (without macVim relaunching) something strange can happen - Vim slows down, plugins can fall into conflict.

So it's better to relaunch macVim completely if .vimrc file was modified.

**Comment by brennier** [comment]
It's probably an autocommand or something that is being loaded twice when you source your .vimrc
