### ISSUE TITLE
Not working after a tab

### ISSUE THREAD

**Issue by Jab2870** [brennier/vimtexer#6]
Hi,

I am using your plugin for various file types and it works excellently, so thanks for your work.

Unfortunately, the shortcuts don't seem to expand when places after a tab.  I normally indent my files with tabs and would like to be able to use one of these shortcuts directly.

I looked through the vim help text for the plugin and couldn't find anything relevant although am surprised that I am the first to raise this so please forgive me if I'm missing something.

**Comment by brennier** [comment]
You're totally right. I suspect that no one has noticed as it's very common to include `set expandtab` in one's vimrc (at least, that's why I didn't notice). I've just sent a commit that should fix this problem. Update the plugin, and let me know if it works for you now.

**Comment by Jab2870** [comment]
Thanks.  That has fixed the issue I was having.  Thanks for your quick responce
