### ISSUE TITLE
Crashes if g:quicktex_math is not set

### ISSUE THREAD

**Issue by igoralmeida** [brennier/vimtexer#7]
Great plugin!
I hit a minor problem, though: if only `g:quicktex_tex` is set in your vimrc, quicktex will crash when pressing e.g. spacebar inside math environments/`$ $`. This is due to a call to `quicktex#expand#ExpandWord` having an undefined `g:quicktex_math`.
I fixed it by adding `let g:quicktex_math = {}` to my vimrc, but perhaps this can be handled more gracefully inside the plugin.

**Comment by brennier** [comment]
Ah, thank you for catching that. I seemed to have missed that case when I rewrote the code from using try/excepts to doing existence checks at startup time. I've just sent a commit that should fix this problem. Update the plugin, and let me know if it works for you now.

**Comment by igoralmeida** [comment]
Thanks, works fine!
